@startuml test

package basecross {

    package Llbs{

        class GameObject {

        }
    }

    package GameSources{

        class StaticGameObject{

        }  
        GameObject <|--StaticGameObject

        class GameManager{

        }
        StaticGameObject <|-- GameManager

        class MyGameObject{

        }
        GameObject <|-- MyGameObject

        class MyCamera {

        }
        MyGameObject <|-- MyCamera

        class Player{

        }

        MyGameObject <|--Player

        class Enemy {

        }
        MyGameObject <|---Enemy

        class NomalEnemy{

        }
        Enemy <|--NomalEnemy

        class ShieldEnemy{

        }
        Enemy <|-- ShieldEnemy

        
        class Speednemy{

        }
        Enemy <|-- Speednemy




    }
}


@enduml